In [13]:
import pandas as pd 
import numpy as np







In [14]:
oneDarray = np.array([1,2,3,4,5,6,7,8,9,10])
print(oneDarray)

[ 1  2  3  4  5  6  7  8  9 10]


In [15]:
print(oneDarray.ndim)

1


In [16]:
TwoDarray = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(TwoDarray)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [17]:
print(TwoDarray.ndim)

2


In [18]:
# indexing 

print(TwoDarray[1,2])

8


In [19]:
# shaping 

print(TwoDarray.shape)

# iteration using numpy 
for i in TwoDarray:
    print(i)
    
    print("")
    
    # outer and inner loop iteration 
for i in TwoDarray:
    for j in i:
        print(j)


(2, 5)
[1 2 3 4 5]

[6 7 8 9 0]

1
2
3
4
5
6
7
8
9
0


In [20]:
threeDarray = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,0,0]]])
print(threeDarray)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 0 0]]]


In [21]:
print(threeDarray.ndim)

3


In [22]:
# indexing of ThreeDarray

print(threeDarray[1,0,1])

8


In [23]:
#  shape of threeDarray 

print(threeDarray.shape)


#  printing threeDarray 

for i in threeDarray:
    for j in i: 
        for k in j:
            print(k)

(2, 2, 3)
1
2
3
4
5
6
7
8
9
0
0
0


In [24]:
#  numby array filled with zeros 

zeroarray = np.zeros((3,3))
print(zeroarray)


#  numby array prefilled with ones 

print("")

onearray = np.ones((3,3))
print(onearray)

print("")
onearray = np.ones((3,3),dtype = int)
print(onearray)


#  numpy array filled with any number

print("")
anyarray = np.full((3,3),5)
print(anyarray)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1 1 1]
 [1 1 1]
 [1 1 1]]

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [25]:
#  adding scaler 

matrix = np.array([[1,2,3,4,5],[6,7,8,9,0]])

print(matrix+2)


[[ 3  4  5  6  7]
 [ 8  9 10 11  2]]


In [26]:
#  subtracting minus complete matrix 

print(matrix-2)


[[-1  0  1  2  3]
 [ 4  5  6  7 -2]]


In [27]:
pythonList = [[1,2,3],[4,5,6]]
print(pythonList+2)




TypeError: can only concatenate list (not "int") to list

In [ ]:

# pyhton mutliply scaler 
print(matrix*2)


[[ 2  4  6  8 10]
 [12 14 16 18  0]]


In [ ]:
print(matrix//2)


[[0 1 1 2 2]
 [3 3 4 4 0]]


In [ ]:
print(pythonList/2)

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [ ]:
print (matrix**3)


[[  1   8  27  64 125]
 [216 343 512 729   0]]


In [ ]:
# transpose 

print(matrix.T)

[[1 6]
 [2 7]
 [3 8]
 [4 9]
 [5 0]]


In [ ]:
name = "John"
print("Hello, " + name + "!")

Hello, John!


In [ ]:
matrix1 = np.array([[1,2,3],[4,5,6]])

matrix2 = np.array([[3,2,1],[6,5,4]])

print(matrix1+matrix2)

[[ 4  4  4]
 [10 10 10]]


In [ ]:
# element wise operation 

# multiply 
print(matrix1*matrix2) 
# plus 
print(matrix1+matrix2)
# minus 
print(matrix1-matrix2)
# division 
print(matrix1/matrix2)

[[ 3  4  3]
 [24 25 24]]
[[ 4  4  4]
 [10 10 10]]
[[-2  0  2]
 [-2  0  2]]
[[0.33333333 1.         3.        ]
 [0.66666667 1.         1.5       ]]


SyntaxError: invalid syntax (2103273119.py, line 1)